name: Daily Checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check diff for reward weights
        run: |
          result=$(scripts/diff-reward-weights.sh) && exit_code=$? || exit_code=$?
          echo "$result"

          {
            echo '```'
            echo "$result"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

          exit "$exit_code"

      - name: Post text to a Slack channel
        if: failure()
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d  # v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID_SUPERVALIDATOR_OPERATIONS }}
            text: "One more more configuration checks failed. Please check the <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|logs> for details."
